# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8890a68446d18c41ce18da2d1a47edba6ffed91f5d21e9232616ac2fa6a7f252dd05b9dde2c7a68cfc082be199c83ac0fd89bdc45e3271ede35a22a6117a0bad

test:
  secret_key_base: 8166b6f28f5f844abf72ceeaf5bdab0c566c2f56f4681587b5bbef1ef33fb6cc9a774cd9c120835806b9004fc23e297e966f3f12e492026245ebbf472d2e7d40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
